(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.RefiningEngine=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const TYPES={
  wood:{labelPl:'Drewno → deski',labelEn:'Wood → planks',raw:'WOOD',refined:'PLANKS',city:'Fort Sterling'},
  fiber:{labelPl:'Włókno → tkanina',labelEn:'Fiber → cloth',raw:'FIBER',refined:'CLOTH',city:'Lymhurst'},
  hide:{labelPl:'Skóra surowa → skóra',labelEn:'Hide → leather',raw:'HIDE',refined:'LEATHER',city:'Martlock'},
  ore:{labelPl:'Ruda → sztaby',labelEn:'Ore → bars',raw:'ORE',refined:'METALBAR',city:'Thetford'},
  stone:{labelPl:'Kamień → bloki',labelEn:'Stone → blocks',raw:'ROCK',refined:'STONEBLOCK',city:'Bridgewatch'}
};
const RAW_QTY={2:1,3:2,4:2,5:3,6:4,7:5,8:5};
function itemId(type,tier,enchant=0,refined=false){const t=TYPES[type];if(!t)throw new Error('Unknown refining type');const base=`T${tier}_${refined?t.refined:t.raw}`;if(refined&&type==='stone')return base;return enchant>0?`${base}_LEVEL${enchant}@${enchant}`:base;}
function previousItemId(type,tier,enchant=0){if(tier<=2)return null;return itemId(type,tier-1,type==='stone'||tier<=4?0:enchant,true);}
function recipe(type,tier,enchant=0){if(!TYPES[type]||!RAW_QTY[tier]||type==='stone'&&enchant>3)return null;return{type,tier,enchant,outputId:itemId(type,tier,enchant,true),rawId:itemId(type,tier,enchant,false),previousId:previousItemId(type,tier,enchant),rawQty:RAW_QTY[tier],previousQty:tier===2?0:1,outputQty:type==='stone'&&enchant>0?2**enchant:1,refiningCity:TYPES[type].city};}
function returnRate({focus=false,dailyBonus=0,bonusCity=true}={}){const bonus=.18+(bonusCity?.40:0)+(focus?.59:0)+Math.max(0,+dailyBonus||0)/100;return bonus/(1+bonus);}
function validTime(v){if(!v||String(v).startsWith('0001-'))return NaN;const s=String(v),z=/[zZ]$|[+\-]\d{2}:?\d{2}$/.test(s);return Date.parse(z?s:s+'Z');}
function selectPrice(rows,itemIdValue,side,markets){const allowed=new Set(markets||[]),candidates=(rows||[]).filter(r=>r.item_id===itemIdValue&&(!allowed.size||allowed.has(r.city))).map(r=>{const price=side==='buy'?+r.sell_price_min:+r.buy_price_max,date=side==='buy'?r.sell_price_min_date:r.buy_price_max_date;return{city:r.city,price,date,row:r};}).filter(x=>x.price>0);candidates.sort((a,b)=>side==='buy'?a.price-b.price||validTime(b.date)-validTime(a.date):b.price-a.price||validTime(b.date)-validTime(a.date));return candidates[0]||null;}
function selectSellOrder(rows,itemIdValue,markets){const allowed=new Set(markets||[]),a=(rows||[]).filter(r=>r.item_id===itemIdValue&&(!allowed.size||allowed.has(r.city))&&+r.sell_price_min>0).map(r=>({city:r.city,price:+r.sell_price_min,date:r.sell_price_min_date,row:r}));a.sort((x,y)=>y.price-x.price||validTime(y.date)-validTime(x.date));return a[0]||null;}
function calculate(recipeValue,rows,cfg={}){const r=recipeValue,markets=cfg.markets||[],raw=selectPrice(rows,r.rawId,'buy',markets),previous=r.previousId?selectPrice(rows,r.previousId,'buy',markets):null,output=cfg.saleMode==='relist'?selectSellOrder(rows,r.outputId,markets):selectPrice(rows,r.outputId,'sell',markets);if(!raw||r.previousId&&!previous||!output)return null;
  const rrr=returnRate({focus:!!cfg.focus,dailyBonus:+cfg.dailyBonus||0,bonusCity:true}),undercut=cfg.saleMode==='relist'?Math.max(0,+cfg.undercutPct||0)/100:0,grossSell=cfg.saleMode==='relist'?Math.max(1,Math.floor(output.price*(1-undercut))):output.price,taxRate=Math.max(0,+cfg.taxPct||0)/100,setupRate=cfg.saleMode==='relist'?Math.max(0,+cfg.setupPct||0)/100:0,netRevenue=grossSell*(1-taxRate-setupRate),grossIngredientsCraft=r.rawQty*raw.price+r.previousQty*(previous?.price||0),effectiveIngredientsCraft=grossIngredientsCraft*(1-rrr),effectiveIngredients=effectiveIngredientsCraft/r.outputQty,stationFee=Math.max(0,+cfg.stationFee||0),transport=Math.max(0,+cfg.transportPerOutput||0),profit=netRevenue-effectiveIngredients-stationFee-transport,unitCost=effectiveIngredients+stationFee+transport,roi=unitCost>0?profit/unitCost*100:null,requestedBatch=Math.max(1,Math.floor(+cfg.batchSize||100)),crafts=Math.ceil(requestedBatch/r.outputQty),batch=crafts*r.outputQty;
  return{...r,raw,previous,output,rrr,grossSell,netRevenue,grossIngredients:grossIngredientsCraft,effectiveIngredients,stationFee,transport,profit,roi,batch,requestedBatch,crafts,grossRawNeeded:r.rawQty*crafts,grossPreviousNeeded:r.previousQty*crafts,expectedRawConsumed:r.rawQty*crafts*(1-rrr),expectedPreviousConsumed:r.previousQty*crafts*(1-rrr),firstBatchCapital:grossIngredientsCraft*crafts+(stationFee+transport)*batch,expectedBatchProfit:profit*batch,saleMode:cfg.saleMode||'instant'};
}
function recipes(types=Object.keys(TYPES),tiers=[2,3,4,5,6,7,8],enchants=[0,1,2,3,4]){const out=[];for(const type of types)for(const tier of tiers)for(const enchant of enchants){if(tier<4&&enchant>0||type==='stone'&&enchant>3)continue;const r=recipe(type,+tier,+enchant);if(r)out.push(r);}return out;}
function requiredItemIds(recipeList){const s=new Set();for(const r of recipeList){s.add(r.rawId);s.add(r.outputId);if(r.previousId)s.add(r.previousId);}return[...s];}
return{TYPES,RAW_QTY,itemId,previousItemId,recipe,recipes,requiredItemIds,returnRate,selectPrice,selectSellOrder,calculate,validTime};
});
