(()=>{'use strict';
const E=window.RefiningEngine,API='https://europe.albion-online-data.com',CITIES=['Bridgewatch','Caerleon','Fort Sterling','Lymhurst','Martlock','Thetford','Brecilien'],el=id=>document.getElementById(id),fmt=n=>Number.isFinite(+n)?Math.round(+n).toLocaleString('pl-PL'):'—',dec=n=>Number.isFinite(+n)?(+n).toLocaleString('pl-PL',{maximumFractionDigits:2}):'—',pct=n=>Number.isFinite(+n)?(+n).toLocaleString('pl-PL',{maximumFractionDigits:1})+'%':'—',esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const age=d=>{const t=E.validTime(d);if(!Number.isFinite(t))return'czas nieznany';const h=Math.max(0,(Date.now()-t)/36e5),dt=new Date(t).toLocaleString('pl-PL',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});return`${dt} • ${h<1?Math.round(h*60)+' min':h<48?h.toFixed(1)+' h':(h/24).toFixed(1)+' d'} temu`;};
const ageHours=d=>{const t=E.validTime(d);return Number.isFinite(t)?Math.max(0,(Date.now()-t)/36e5):Infinity;};
let results=[],sortKey='freshness',sortDir='desc',running=false,lastRecipes=[],lastRows=[],lastScopeKey='';
const NAMES={wood:{raw:'Drewno',refined:'Deski'},fiber:{raw:'Włókno',refined:'Tkanina'},hide:{raw:'Surowa skóra',refined:'Wyprawiona skóra'},ore:{raw:'Ruda',refined:'Sztaby metalu'},stone:{raw:'Kamień',refined:'Bloki kamienne'}};
function tierText(t){return`poziom ${t} (T${t})`;}
function enchantText(e){return e===0?'bez zaczarowania (.0)':`zaczarowanie ${e} (.${e})`;}
function routeText(x){return x.route==='heart'?'receptura z sercem frakcji':'receptura standardowa';}
function variantText(x){return`${tierText(x.tier)}, ${enchantText(x.enchant)}, ${routeText(x)}`;}
function rawName(x){return`${NAMES[x.type].raw} — ${tierText(x.tier)}, ${enchantText(x.enchant)}`;}
function outputName(x){return x.type==='stone'?`${NAMES[x.type].refined} — ${tierText(x.tier)}${x.enchant>0?' (zwykłe bloki)':''}`:`${NAMES[x.type].refined} — ${tierText(x.tier)}, ${enchantText(x.enchant)}`;}
function previousName(x){if(!x.previousId)return'';const t=x.tier-1,e=x.type==='stone'||x.tier<=4?0:x.enchant;return`${NAMES[x.type].refined} — ${tierText(t)}, ${enchantText(e)}`;}
function heartName(x){return E.TYPES[x.type].heartPl;}
function checked(cls){return[...document.querySelectorAll('.'+cls+':checked')].map(x=>x.value);}
function valueMap(cls,key='type'){return Object.fromEntries([...document.querySelectorAll('.'+cls)].map(x=>[x.dataset[key],+x.value||0]));}
function specsMap(){const out={};for(const type of Object.keys(E.TYPES))out[type]={};for(const x of document.querySelectorAll('.specInput'))out[x.dataset.type][x.dataset.tier]=+x.value||0;return out;}
function cfg(){return{markets:checked('cityCheck'),saleMode:el('saleMode').value,focus:el('focus').checked,dailyBonuses:valueMap('dailyBonusInput'),taxPct:el('premium').value==='yes'?4:8,setupPct:+el('setupPct').value||0,undercutPct:+el('undercutPct').value||0,stationFees:valueMap('stationFeeInput'),transportPerOutput:+el('transport').value||0,batchSize:+el('batchSize').value||100,confirmedBatch:+el('confirmedBatch').value||0,focusBudget:+el('focusBudget').value||0,specsByType:specsMap(),freshnessHours:+el('freshnessHours').value||24};}
function scope(){return{types:checked('typeCheck'),tiers:checked('tierCheck').map(Number),enchants:checked('enchantCheck').map(Number),includeHearts:el('includeHearts').checked};}
function scopeKey(s=scope(),markets=cfg().markets){return JSON.stringify({types:[...s.types].sort(),tiers:[...s.tiers].sort((a,b)=>a-b),enchants:[...s.enchants].sort((a,b)=>a-b),markets:[...markets].sort(),includeHearts:s.includeHearts});}
function priceUrl(ids,markets){return`${API}/api/v2/stats/prices/${encodeURIComponent(ids.join(',')).replace(/%2C/g,',')}.json?locations=${encodeURIComponent(markets.join(','))}&qualities=1`;}
function batches(ids,markets){const out=[];let b=[];for(const id of ids){const next=[...b,id];if(priceUrl(next,markets).length>3300&&b.length){out.push(b);b=[id];}else b=next;}if(b.length)out.push(b);return out;}
async function fetchRetry(url){let err;for(let n=0;n<3;n++){try{const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);return await r.json();}catch(e){err=e;await new Promise(res=>setTimeout(res,1200*(n+1)));}}throw err;}
function status(text,p=0){el('status').textContent=text;el('bar').style.width=Math.max(0,Math.min(100,p))+'%';}
function setBusy(value){running=value;el('scan').disabled=value;el('refresh').disabled=value||!lastRecipes.length;}
function recalculate(c=cfg()){results=lastRecipes.map(r=>E.calculate(r,lastRows,c)).filter(Boolean).sort((a,b)=>b.profit-a.profit);render();}
async function fetchPrices(ids,markets,prefix){const bs=batches(ids,markets),rows=[];for(let i=0;i<bs.length;i++){status(`${prefix}: partia ${i+1}/${bs.length}`,5+78*(i/Math.max(1,bs.length)));const j=await fetchRetry(priceUrl(bs[i],markets));if(Array.isArray(j))rows.push(...j);}return rows;}
function mergeRefreshedRows(ids,markets,fresh){const idSet=new Set(ids),marketSet=new Set(markets),kept=lastRows.filter(r=>!(idSet.has(r.item_id)&&marketSet.has(r.city))),map=new Map();for(const r of [...kept,...fresh])map.set(`${r.item_id}|${r.city}|${+r.quality||1}`,r);lastRows=[...map.values()];}
async function scan(){if(running)return;const s=scope(),c=cfg();if(!s.types.length||!s.tiers.length||!s.enchants.length)return alert('Wybierz rodzaj surowca, poziom przedmiotu oraz poziom zaczarowania.');if(!c.markets.length)return alert('Wybierz co najmniej jedno miasto.');setBusy(true);results=[];lastRecipes=[];lastRows=[];render();try{const rs=E.recipes(s.types,s.tiers,s.enchants,{includeHearts:s.includeHearts}),ids=E.requiredItemIds(rs);lastRows=await fetchPrices(ids,c.markets,'Pełny skan cen');lastRecipes=rs;lastScopeKey=scopeKey(s,c.markets);status('Obliczanie wariantów rafinacji…',88);recalculate(c);status(`Pełny skan gotowy: ${results.length} kompletnych wariantów z ${rs.length}. Wynik partii jest szacunkiem, dopóki nie potwierdzisz ilości ofert w grze.`,100);}catch(e){lastRecipes=[];lastRows=[];status('Błąd: '+(e?.message||e),0);}finally{setBusy(false);}}
async function refreshPrices(){if(running||!lastRecipes.length)return;if(scopeKey()!==lastScopeKey)return alert('Zmieniono surowce, poziomy, zaczarowania, receptury z sercami albo miasta. Dla nowego zakresu uruchom pełny skan.');const c=cfg(),limitValue=el('refreshLimit').value,limit=limitValue==='all'?results.length:Math.max(1,+limitValue||30),top=[...results].sort((a,b)=>b.profit-a.profit).slice(0,limit),keys=new Set(top.map(x=>`${x.type}|${x.tier}|${x.enchant}|${x.route}`)),selected=lastRecipes.filter(r=>keys.has(`${r.type}|${r.tier}|${r.enchant}|${r.route}`));if(!selected.length)return alert('Brak istniejących wyników do odświeżenia.');const ids=E.requiredItemIds(selected);setBusy(true);try{const fresh=await fetchPrices(ids,c.markets,`Szybkie odświeżanie ${selected.length} wyników`);mergeRefreshedRows(ids,c.markets,fresh);status('Ponowne liczenie zysku…',90);recalculate(c);status(`Odświeżono ceny dla ${selected.length} pozycji (${ids.length} unikalnych przedmiotów). Pozostałe wyniki zachowują wcześniejsze notowania.`,100);}catch(e){status('Błąd odświeżania: '+(e?.message||e),0);}finally{setBusy(false);}}
function compare(a,b){const val=o=>sortKey==='material'?`${E.TYPES[o.type].labelPl} T${o.tier}.${o.enchant} ${o.route}`:sortKey==='city'?o.refiningCity:sortKey==='rawTime'?E.validTime(o.raw.date):sortKey==='previousTime'?E.validTime(o.previous?.date||o.heart?.date):sortKey==='sellTime'?E.validTime(o.output.date):sortKey==='freshness'?E.validTime(o.oldestQuoteDate):sortKey==='roi'?o.roi:sortKey==='rrr'?o.rrr:sortKey==='focus'?o.profitPerFocus:o.profit,va=val(a),vb=val(b);const n=typeof va==='string'?va.localeCompare(vb,'pl'):(Number.isFinite(+va)?+va:-Infinity)-(Number.isFinite(+vb)?+vb:-Infinity);return sortDir==='asc'?n:-n;}
function staleInfo(x,c=cfg()){const h=ageHours(x.oldestQuoteDate);return{hours:h,stale:h>c.freshnessHours,text:Number.isFinite(h)?age(x.oldestQuoteDate):'czas nieznany'};}
function render(){const c=cfg(),a=[...results].sort(compare),bestOp=results.length?results.reduce((best,x)=>x.profit>best.profit?x:best,results[0]):null;el('count').textContent=fmt(a.length);el('best').textContent=bestOp?`${E.TYPES[bestOp.type].labelPl} — ${variantText(bestOp)}`:'—';el('bestProfit').textContent=bestOp?fmt(bestOp.profit):'—';el('tbody').innerHTML=a.map((x,i)=>{const st=staleInfo(x,c),other=[x.previous?`<b>${esc(x.previous.city)}</b><small>${esc(previousName(x))}<br>${fmt(x.previous.price)} srebra / szt.<br>Cena z: ${esc(age(x.previous.date))}</small>`:'',x.heart?`<b>${esc(x.heart.city)}</b><small>${esc(heartName(x))}<br>${fmt(x.heart.price)} srebra / szt.<br>Cena z: ${esc(age(x.heart.date))}</small>`:''].filter(Boolean).join('<hr>')||'Nie są potrzebne',focus=x.focusPerCraft?`${fmt(x.profitPerFocus)}<small>srebra / 1 focus<br>${fmt(x.focusUsed)} / ${fmt(x.focusBudget)} focusu</small>`:'—',batch=x.confirmedBatch==null?`≈ ${x.expectedBatchProfit>=0?'+':''}${fmt(x.expectedBatchProfit)}<small>szacunek — ilość ofert niepotwierdzona</small>`:`${x.confirmedBatchProfit>=0?'+':''}${fmt(x.confirmedBatchProfit)}<small>dla potwierdzonych ${fmt(x.confirmedBatch)} szt.</small>`;return`<tr class="${x.profit>0?'positive':'negative'}${st.stale?' stale':''}"><td><button class="details" data-i="${i}">Pokaż plan</button></td><td><b>${esc(E.TYPES[x.type].labelPl)}</b><small>Produkt: ${esc(outputName(x))}</small></td><td><b>${esc(tierText(x.tier))}</b><small>${esc(enchantText(x.enchant))}<br>${esc(routeText(x))}</small></td><td><b>${esc(x.raw.city)}</b><small>${esc(rawName(x))}<br>${fmt(x.raw.price)} srebra / szt.<br>Cena z: ${esc(age(x.raw.date))}</small></td><td>${other}</td><td><b>${esc(x.refiningCity)}</b><small>miasto z premią<br>stacja: ${dec(x.stationFee)} / gotową szt.</small></td><td><b>${pct(x.rrr*100)}</b><small>średni zwrot</small></td><td><b>${esc(x.output.city)}</b><small>${fmt(x.grossSell)} srebra / szt.<br>Cena z: ${esc(age(x.output.date))}</small></td><td class="${st.stale?'warn':''}"><b>${esc(st.text)}</b><small>${st.stale?'uwaga: przekroczony ustawiony próg':'najstarsza użyta cena'}</small></td><td>${fmt(x.effectiveIngredients+x.stationFee+x.transport)} srebra</td><td class="money">${x.profit>=0?'+':''}${fmt(x.profit)} srebra</td><td>${pct(x.roi)}</td><td>${focus}</td><td class="money">${batch}</td></tr>`;}).join('');document.querySelectorAll('.details').forEach((b,i)=>b.onclick=()=>details(a[i]));document.querySelectorAll('th[data-sort]').forEach(th=>{th.classList.toggle('active',th.dataset.sort===sortKey);th.onclick=()=>{if(sortKey===th.dataset.sort)sortDir=sortDir==='asc'?'desc':'asc';else{sortKey=th.dataset.sort;sortDir=['material','city'].includes(sortKey)?'asc':'desc';}render();};});}
function details(x){el('dialogTitle').textContent=`${E.TYPES[x.type].labelPl} — ${variantText(x)}`;const st=staleInfo(x),prev=x.previous?`<li><b>Materiał poprzedniego poziomu:</b> kup <b>${fmt(x.grossPreviousNeeded)} szt.</b> produktu „${esc(previousName(x))}” w mieście <b>${esc(x.previous.city)}</b> po ${fmt(x.previous.price)} srebra za sztukę.<small>Cena zapisana: ${esc(age(x.previous.date))}</small></li>`:'',heart=x.heart?`<li><b>Serce frakcji:</b> kup <b>${fmt(x.grossHeartNeeded)} szt.</b> produktu „${esc(heartName(x))}” w mieście <b>${esc(x.heart.city)}</b> po ${fmt(x.heart.price)} srebra za sztukę.<small>Cena zapisana: ${esc(age(x.heart.date))}</small></li>`:'',stoneInfo=x.outputQty>1?`<p class="note"><b>Receptura zaczarowanego kamienia:</b> jedno użycie stacji zużywa ${fmt(x.rawQty)} szt. kamienia oraz <b>${fmt(x.previousQty)} bloków poprzedniego tieru</b> i daje ${x.outputQty} zwykłych bloków. Plan wykonuje ${fmt(x.crafts)} rafinacji i daje ${fmt(x.batch)} bloków.</p>`:'',focusInfo=x.focusPerCraft?`<h3>Focus i specjalizacja</h3><div class="calc"><span>Bazowy focus / użycie stacji</span><b>${fmt(x.focusBase)}</b><span>Efektywność focusu z podanych specjalizacji</span><b>${fmt(x.focusEfficiency)}</b><span>Rzeczywisty focus / użycie stacji</span><b>${fmt(x.focusPerCraft)}</b><span>Focus potrzebny dla żądanej partii</span><b>${fmt(x.focusNeeded)}</b><span>Focus wykorzystany przez plan</span><b>${fmt(x.focusUsed)} / ${fmt(x.focusBudget)}</b><span>Dodatkowy zysk na 1 focus</span><b>${dec(x.profitPerFocus)} srebra</b></div>${x.batchLimitedByFocus?`<p class="warning"><b>Partia została ograniczona focusem.</b> Brakuje focusu na ${fmt(x.missingOutputQty)} żądanych gotowych sztuk.</p>`:''}`:'',availability=x.confirmedBatch==null?`<p class="warning"><b>Ważne:</b> AODP podaje najlepszą cenę, ale nie liczbę sztuk dostępnych po tej cenie. Zysk całej partii <b>${x.expectedBatchProfit>=0?'+':''}${fmt(x.expectedBatchProfit)}</b> jest tylko szacunkiem. Sprawdź ilości zleceń w grze albo wpisz potwierdzoną bezpieczną partię w ustawieniach.</p>`:`<p class="ok"><b>Potwierdzona partia:</b> wynik ${x.confirmedBatchProfit>=0?'+':''}${fmt(x.confirmedBatchProfit)} srebra dotyczy najwyżej ${fmt(x.confirmedBatch)} sztuk wpisanych w ustawieniach.</p>`,heartConsumed=x.heart?`<li>${dec(x.expectedHeartConsumed)} szt. — ${esc(heartName(x))}</li>`:'';
  el('dialogBody').innerHTML=`<div class="cards"><div><span>Miasto rafinacji</span><b>${esc(x.refiningCity)}</b></div><div><span>Miasto sprzedaży</span><b>${esc(x.output.city)}</b></div><div><span>Średni odzysk materiałów</span><b>${pct(x.rrr*100)}</b></div><div><span>${x.confirmedBatch==null?'Szacowany zysk partii':'Zysk potwierdzonej partii'}</span><b class="profit">${x.confirmedBatch==null?(x.expectedBatchProfit>=0?'+':'')+fmt(x.expectedBatchProfit):(x.confirmedBatchProfit>=0?'+':'')+fmt(x.confirmedBatchProfit)} srebra</b></div></div><p class="${st.stale?'warning':'note'}"><b>Najstarsza cena użyta w tym wyniku:</b> ${esc(st.text)}.${x.quoteSpreadHours?` Rozpiętość czasów wszystkich cen: ${dec(x.quoteSpreadHours)} h.`:''}</p>${availability}${stoneInfo}<h3>Co dokładnie kupić</h3><p class="note">Plan zakłada ${fmt(x.crafts)} użyć stacji rafinacji i produkcję ${fmt(x.batch)} gotowych sztuk. Wybrano: ${esc(routeText(x))}.</p><ul><li><b>Główny surowiec:</b> kup <b>${fmt(x.grossRawNeeded)} szt.</b> produktu „${esc(rawName(x))}” w mieście <b>${esc(x.raw.city)}</b> po ${fmt(x.raw.price)} srebra za sztukę.<small>Cena zapisana: ${esc(age(x.raw.date))}</small></li>${prev}${heart}</ul><h3>Ile materiałów zostanie średnio zużyte</h3><p class="note">Część materiałów wraca po rafinacji. Dlatego średnie zużycie jest mniejsze od liczby, którą trzeba mieć przed rozpoczęciem produkcji.</p><ul><li>${dec(x.expectedRawConsumed)} szt. — ${esc(rawName(x))}</li>${x.previous?`<li>${dec(x.expectedPreviousConsumed)} szt. — ${esc(previousName(x))}</li>`:''}${heartConsumed}</ul><div class="calc"><span>Srebro potrzebne do rozpoczęcia partii</span><b>${fmt(x.firstBatchCapital)}</b><span>Średni koszt materiałów na 1 gotową sztukę</span><b>${fmt(x.effectiveIngredients)}</b><span>Opłata stacji na 1 gotową sztukę</span><b>${dec(x.stationFee)}</b><span>Podstawa opłaty stacji</span><b>${fmt(x.stationFeePer100)} srebra / 100 odżywienia; item value ${fmt(x.itemValue)}</b><span>Koszt transportu na 1 gotową sztukę</span><b>${fmt(x.transport)}</b><span>Opłata za wystawienie na 1 sztukę</span><b>${dec(x.setupFee)}</b><span>Kwota ze sprzedaży po podatkach na 1 sztukę</span><b>${fmt(x.netRevenue)}</b><span>Zysk na 1 gotowej sztuce</span><b class="profit">${x.profit>=0?'+':''}${fmt(x.profit)}</b></div>${focusInfo}<details class="technical"><summary>Pokaż techniczne identyfikatory danych</summary><p>Surowiec: ${esc(x.rawId)}<br>${x.previousId?`Materiał poprzedniego poziomu: ${esc(x.previousId)}<br>`:''}${x.heartId?`Serce frakcji: ${esc(x.heartId)}<br>`:''}Gotowy produkt: ${esc(x.outputId)}</p></details><p class="note">Odzysk materiałów jest wartością statystyczną. Przy małej liczbie produkcji rzeczywisty wynik może się nieznacznie różnić.</p>`;el('dialog').showModal();}
function initDynamicInputs(){el('dailyBonuses').innerHTML=Object.entries(E.TYPES).map(([k,v])=>`<div class="field"><span>${esc(v.labelPl)}</span><select class="dailyBonusInput" data-type="${k}"><option value="0">Brak</option><option value="10">+10%</option><option value="20">+20%</option></select></div>`).join('');el('stationFees').innerHTML=Object.entries(E.TYPES).map(([k,v])=>`<div class="field"><span>${esc(v.labelPl)} — ${esc(v.city)}</span><input class="stationFeeInput" data-type="${k}" type="number" min="0" step="1" value="0"></div>`).join('');el('specGrid').innerHTML=`<div class="spec-head"><b>Surowiec</b>${[4,5,6,7,8].map(t=>`<b>T${t}</b>`).join('')}</div>${Object.entries(E.TYPES).map(([k,v])=>`<div class="spec-row"><span>${esc(v.labelPl.split(' → ')[0])}</span>${[4,5,6,7,8].map(t=>`<input class="specInput" data-type="${k}" data-tier="${t}" aria-label="${esc(v.labelPl)} specjalizacja T${t}" type="number" min="0" max="100" step="1" value="0">`).join('')}</div>`).join('')}`;}
function init(){el('cities').innerHTML=CITIES.map(c=>`<label><input class="cityCheck" type="checkbox" value="${c}" checked> ${c}</label>`).join('');el('types').innerHTML=Object.entries(E.TYPES).map(([k,v])=>`<label><input class="typeCheck" type="checkbox" value="${k}" checked> ${v.labelPl}</label>`).join('');el('tiers').innerHTML=[2,3,4,5,6,7,8].map(t=>`<label><input class="tierCheck" type="checkbox" value="${t}" checked> Poziom ${t} (T${t})</label>`).join('');el('enchants').innerHTML=[0,1,2,3,4].map(e=>`<label><input class="enchantCheck" type="checkbox" value="${e}" ${e<4?'checked':''}> ${e===0?'Brak (.0)':`Zaczarowanie ${e} (.${e})`}</label>`).join('');initDynamicInputs();el('scan').onclick=scan;el('refresh').onclick=refreshPrices;el('close').onclick=()=>el('dialog').close();document.querySelectorAll('input,select').forEach(x=>x.addEventListener('change',e=>{if(!lastRecipes.length)return;const full=e.target.matches('.cityCheck,.typeCheck,.tierCheck,.enchantCheck,#includeHearts');if(full)status('Zmieniono zakres produktów, receptur lub miasta — uruchom ponownie pełny skan.',0);else if(e.target.id!=='refreshLimit'){recalculate();status('Przeliczono wyniki z zapisanych cen. Użyj „Odśwież ceny”, aby pobrać nowsze notowania.',0);}}));render();}
init();})();
