(()=>{'use strict';
const E=window.RefiningEngine,API='https://europe.albion-online-data.com',CITIES=['Bridgewatch','Caerleon','Fort Sterling','Lymhurst','Martlock','Thetford','Brecilien'],el=id=>document.getElementById(id),fmt=n=>Number.isFinite(+n)?Math.round(+n).toLocaleString('pl-PL'):'—',pct=n=>Number.isFinite(+n)?(+n).toLocaleString('pl-PL',{maximumFractionDigits:1})+'%':'—',esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),age=d=>{const t=E.validTime(d);if(!Number.isFinite(t))return'czas nieznany';const h=Math.max(0,(Date.now()-t)/36e5),dt=new Date(t).toLocaleString('pl-PL',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});return`${dt} • ${h<1?Math.round(h*60)+' min':h<48?h.toFixed(1)+' h':(h/24).toFixed(1)+' d'} temu`;};
let results=[],sortKey='profit',sortDir='desc',running=false,lastRecipes=[],lastRows=[],lastScopeKey='';
function checked(cls){return[...document.querySelectorAll('.'+cls+':checked')].map(x=>x.value);}
function cfg(){return{markets:checked('cityCheck'),saleMode:el('saleMode').value,focus:el('focus').checked,dailyBonus:+el('dailyBonus').value||0,taxPct:el('premium').value==='yes'?4:8,setupPct:+el('setupPct').value||0,undercutPct:+el('undercutPct').value||0,stationFee:+el('stationFee').value||0,transportPerOutput:+el('transport').value||0,batchSize:+el('batchSize').value||100};}
function scope(){return{types:checked('typeCheck'),tiers:checked('tierCheck').map(Number),enchants:checked('enchantCheck').map(Number)};}
function scopeKey(s=scope(),markets=cfg().markets){return JSON.stringify({types:[...s.types].sort(),tiers:[...s.tiers].sort((a,b)=>a-b),enchants:[...s.enchants].sort((a,b)=>a-b),markets:[...markets].sort()});}
function priceUrl(ids,markets){return`${API}/api/v2/stats/prices/${encodeURIComponent(ids.join(',')).replace(/%2C/g,',')}.json?locations=${encodeURIComponent(markets.join(','))}&qualities=1`;}
function batches(ids,markets){const out=[];let b=[];for(const id of ids){const next=[...b,id];if(priceUrl(next,markets).length>3300&&b.length){out.push(b);b=[id];}else b=next;}if(b.length)out.push(b);return out;}
async function fetchRetry(url){let err;for(let n=0;n<3;n++){try{const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);return await r.json();}catch(e){err=e;await new Promise(res=>setTimeout(res,1200*(n+1)));}}throw err;}
function status(text,p=0){el('status').textContent=text;el('bar').style.width=Math.max(0,Math.min(100,p))+'%';}
function setBusy(value){running=value;el('scan').disabled=value;el('refresh').disabled=value||!lastRecipes.length;}
function recalculate(c=cfg()){results=lastRecipes.map(r=>E.calculate(r,lastRows,c)).filter(Boolean).sort((a,b)=>b.profit-a.profit);render();}
async function fetchPrices(ids,markets,prefix){const bs=batches(ids,markets),rows=[];for(let i=0;i<bs.length;i++){status(`${prefix}: partia ${i+1}/${bs.length}`,5+78*(i/Math.max(1,bs.length)));const j=await fetchRetry(priceUrl(bs[i],markets));if(Array.isArray(j))rows.push(...j);}return rows;}
function mergeRefreshedRows(ids,markets,fresh){const idSet=new Set(ids),marketSet=new Set(markets),kept=lastRows.filter(r=>!(idSet.has(r.item_id)&&marketSet.has(r.city))),map=new Map();for(const r of [...kept,...fresh])map.set(`${r.item_id}|${r.city}|${+r.quality||1}`,r);lastRows=[...map.values()];}
async function scan(){if(running)return;const s=scope(),c=cfg();if(!s.types.length||!s.tiers.length||!s.enchants.length)return alert('Wybierz surowiec, tier i enchant.');if(!c.markets.length)return alert('Wybierz co najmniej jeden market.');setBusy(true);results=[];lastRecipes=[];lastRows=[];render();try{const rs=E.recipes(s.types,s.tiers,s.enchants),ids=E.requiredItemIds(rs);lastRows=await fetchPrices(ids,c.markets,'Pełny skan cen');lastRecipes=rs;lastScopeKey=scopeKey(s,c.markets);status('Obliczanie wariantów rafinacji…',88);recalculate(c);status(`Pełny skan gotowy: ${results.length} kompletnych wariantów z ${rs.length}. Możesz teraz używać szybkiego odświeżania.`,100);}catch(e){lastRecipes=[];lastRows=[];status('Błąd: '+(e?.message||e),0);}finally{setBusy(false);}}
async function refreshPrices(){if(running||!lastRecipes.length)return;if(scopeKey()!==lastScopeKey)return alert('Zmieniono surowce, tiery, enchanty albo miasta. Dla nowego zakresu uruchom pełny skan.');const c=cfg(),limitValue=el('refreshLimit').value,limit=limitValue==='all'?results.length:Math.max(1,+limitValue||30),top=[...results].sort((a,b)=>b.profit-a.profit).slice(0,limit),keys=new Set(top.map(x=>`${x.type}|${x.tier}|${x.enchant}`)),selected=lastRecipes.filter(r=>keys.has(`${r.type}|${r.tier}|${r.enchant}`));if(!selected.length)return alert('Brak istniejących wyników do odświeżenia.');const ids=E.requiredItemIds(selected);setBusy(true);try{const fresh=await fetchPrices(ids,c.markets,`Szybkie odświeżanie ${selected.length} wyników`);mergeRefreshedRows(ids,c.markets,fresh);status('Ponowne liczenie profitu…',90);recalculate(c);status(`Odświeżono ceny dla ${selected.length} pozycji (${ids.length} unikalnych przedmiotów). Pozostałe wyniki zachowują wcześniejsze notowania.`,100);}catch(e){status('Błąd odświeżania: '+(e?.message||e),0);}finally{setBusy(false);}}
function compare(a,b){const val=o=>sortKey==='material'?`${E.TYPES[o.type].labelPl} T${o.tier}.${o.enchant}`:sortKey==='city'?o.refiningCity:sortKey==='rawCity'?o.raw.city:sortKey==='sellCity'?o.output.city:sortKey==='roi'?o.roi:sortKey==='rrr'?o.rrr:o.profit,va=val(a),vb=val(b);const n=typeof va==='string'?va.localeCompare(vb,'pl'):(+va||0)-(+vb||0);return sortDir==='asc'?n:-n;}
function render(){const a=[...results].sort(compare),bestOp=results.length?results.reduce((best,x)=>x.profit>best.profit?x:best,results[0]):null;el('count').textContent=fmt(a.length);el('best').textContent=bestOp?`${E.TYPES[bestOp.type].labelPl} T${bestOp.tier}.${bestOp.enchant}`:'—';el('bestProfit').textContent=bestOp?fmt(bestOp.profit):'—';el('tbody').innerHTML=a.map((x,i)=>`<tr class="${x.profit>0?'positive':'negative'}"><td><button class="details" data-i="${i}">Szczegóły</button></td><td><b>${esc(E.TYPES[x.type].labelPl)}</b><small>${esc(x.outputId)}</small></td><td>T${x.tier}.${x.enchant}</td><td><b>${esc(x.raw.city)}</b><small>${fmt(x.raw.price)} / szt.<br>${esc(age(x.raw.date))}</small></td><td>${x.previous?`<b>${esc(x.previous.city)}</b><small>${fmt(x.previous.price)} / szt.<br>${esc(age(x.previous.date))}</small>`:'—'}</td><td><b>${esc(x.refiningCity)}</b><small>premia surowca</small></td><td>${pct(x.rrr*100)}</td><td><b>${esc(x.output.city)}</b><small>${fmt(x.grossSell)} / szt.<br>${esc(age(x.output.date))}</small></td><td>${fmt(x.effectiveIngredients+x.stationFee+x.transport)}</td><td class="money">${x.profit>=0?'+':''}${fmt(x.profit)}</td><td>${pct(x.roi)}</td><td class="money">${x.expectedBatchProfit>=0?'+':''}${fmt(x.expectedBatchProfit)}</td></tr>`).join('');document.querySelectorAll('.details').forEach((b,i)=>b.onclick=()=>details(a[i]));document.querySelectorAll('th[data-sort]').forEach(th=>{th.classList.toggle('active',th.dataset.sort===sortKey);th.onclick=()=>{if(sortKey===th.dataset.sort)sortDir=sortDir==='asc'?'desc':'asc';else{sortKey=th.dataset.sort;sortDir=['material','city','rawCity','sellCity'].includes(sortKey)?'asc':'desc';}render();};});}
function details(x){el('dialogTitle').textContent=`${E.TYPES[x.type].labelPl} T${x.tier}.${x.enchant}`;const prev=x.previous?`<li><b>${fmt(x.grossPreviousNeeded)}</b> × ${esc(x.previousId)} — kup w <b>${esc(x.previous.city)}</b> po ${fmt(x.previous.price)}; odczyt ${esc(age(x.previous.date))}</li>`:'',stoneInfo=x.outputQty>1?`<p class="note">Jedna rafinacja zaczarowanego kamienia daje <b>${x.outputQty}</b> × ${esc(x.outputId)}. Aby uzyskać co najmniej ${fmt(x.requestedBatch)} bloków, plan wykonuje ${fmt(x.crafts)} rafinacji i daje ${fmt(x.batch)} bloków.</p>`:'';el('dialogBody').innerHTML=`<div class="cards"><div><span>Rafinuj w</span><b>${esc(x.refiningCity)}</b></div><div><span>Sprzedaj w</span><b>${esc(x.output.city)}</b></div><div><span>Zwrot surowców</span><b>${pct(x.rrr*100)}</b></div><div><span>Profit partii</span><b class="profit">${x.expectedBatchProfit>=0?'+':''}${fmt(x.expectedBatchProfit)}</b></div></div>${stoneInfo}<h3>Lista zakupów — ${fmt(x.crafts)} rafinacji / ${fmt(x.batch)} gotowych szt.</h3><ul><li><b>${fmt(x.grossRawNeeded)}</b> × ${esc(x.rawId)} — kup w <b>${esc(x.raw.city)}</b> po ${fmt(x.raw.price)}; odczyt ${esc(age(x.raw.date))}</li>${prev}</ul><h3>Oczekiwane zużycie po zwrotach</h3><ul><li>${x.expectedRawConsumed.toLocaleString('pl-PL',{maximumFractionDigits:1})} × ${esc(x.rawId)}</li>${x.previous?`<li>${x.expectedPreviousConsumed.toLocaleString('pl-PL',{maximumFractionDigits:1})} × ${esc(x.previousId)}</li>`:''}</ul><div class="calc"><span>Kapitał pierwszej partii</span><b>${fmt(x.firstBatchCapital)}</b><span>Efektywny koszt składników / gotową szt.</span><b>${fmt(x.effectiveIngredients)}</b><span>Opłata stacji / gotową szt.</span><b>${fmt(x.stationFee)}</b><span>Transport / gotową szt.</span><b>${fmt(x.transport)}</b><span>Przychód netto / szt.</span><b>${fmt(x.netRevenue)}</b><span>Zysk / szt.</span><b class="profit">${x.profit>=0?'+':''}${fmt(x.profit)}</b></div><p class="note">Lista zakupów pokazuje pełną liczbę materiałów potrzebną do uruchomienia pierwszej partii. „Oczekiwane zużycie” uwzględnia statystyczny zwrot surowców i jest podstawą obliczenia zysku. Faktyczny zwrot małej partii może się różnić.</p>`;el('dialog').showModal();}
function init(){el('cities').innerHTML=CITIES.map(c=>`<label><input class="cityCheck" type="checkbox" value="${c}" checked> ${c}</label>`).join('');el('types').innerHTML=Object.entries(E.TYPES).map(([k,v])=>`<label><input class="typeCheck" type="checkbox" value="${k}" checked> ${v.labelPl}</label>`).join('');el('tiers').innerHTML=[2,3,4,5,6,7,8].map(t=>`<label><input class="tierCheck" type="checkbox" value="${t}" checked> T${t}</label>`).join('');el('enchants').innerHTML=[0,1,2,3,4].map(e=>`<label><input class="enchantCheck" type="checkbox" value="${e}" ${e<4?'checked':''}> .${e}</label>`).join('');el('scan').onclick=scan;el('refresh').onclick=refreshPrices;el('close').onclick=()=>el('dialog').close();document.querySelectorAll('input,select').forEach(x=>x.addEventListener('change',e=>{if(!lastRecipes.length)return;const full=e.target.matches('.cityCheck,.typeCheck,.tierCheck,.enchantCheck');if(full)status('Zakres skanu został zmieniony — wymagany pełny skan.',0);else if(e.target.id!=='refreshLimit'){recalculate();status('Przeliczono wyniki z zapisanych cen. Użyj „Odśwież ceny”, aby pobrać nowsze notowania.',0);}}));render();}
init();})();
