(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.RefiningEngine=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const TYPES={
  wood:{labelPl:'Drewno → deski',labelEn:'Wood → planks',raw:'WOOD',refined:'PLANKS',city:'Fort Sterling',heart:'T1_FACTION_FOREST_TOKEN_1',heartPl:'Serce frakcji do rafinacji drewna'},
  fiber:{labelPl:'Włókno → tkanina',labelEn:'Fiber → cloth',raw:'FIBER',refined:'CLOTH',city:'Lymhurst',heart:'T1_FACTION_SWAMP_TOKEN_1',heartPl:'Serce frakcji do rafinacji włókna'},
  hide:{labelPl:'Skóra surowa → skóra',labelEn:'Hide → leather',raw:'HIDE',refined:'LEATHER',city:'Martlock',heart:'T1_FACTION_STEPPE_TOKEN_1',heartPl:'Serce frakcji do rafinacji skóry'},
  ore:{labelPl:'Ruda → sztaby',labelEn:'Ore → bars',raw:'ORE',refined:'METALBAR',city:'Thetford',heart:'T1_FACTION_MOUNTAIN_TOKEN_1',heartPl:'Serce frakcji do rafinacji rudy'},
  stone:{labelPl:'Kamień → bloki',labelEn:'Stone → blocks',raw:'ROCK',refined:'STONEBLOCK',city:'Bridgewatch',heart:'T1_FACTION_HIGHLAND_TOKEN_1',heartPl:'Serce frakcji do rafinacji kamienia'}
};
const RAW_QTY={2:1,3:2,4:2,5:3,6:4,7:5,8:5};
const FOCUS_BASE={
  2:{0:18},3:{0:31},
  4:{0:54,1:94,2:164,3:287,4:503},
  5:{0:94,1:164,2:287,3:503,4:880},
  6:{0:164,1:287,2:503,3:880,4:1539},
  7:{0:287,1:503,2:880,3:1539,4:2694},
  8:{0:503,1:880,2:1539,3:2694,4:4714}
};
function itemId(type,tier,enchant=0,refined=false){const t=TYPES[type];if(!t)throw new Error('Unknown refining type');const base=`T${tier}_${refined?t.refined:t.raw}`;if(refined&&type==='stone')return base;return enchant>0?`${base}_LEVEL${enchant}@${enchant}`:base;}
function previousItemId(type,tier,enchant=0){if(tier<=2)return null;return itemId(type,tier-1,type==='stone'||tier<=4?0:enchant,true);}
function supportsHeart(type,tier,enchant=0){return!!TYPES[type]&&tier>=4&&(type==='stone'?enchant===0:enchant<=3);}
function outputItemValue(type,tier,enchant=0){return 2**(tier+(type==='stone'?0:enchant));}
function baseFocusCost(type,tier,enchant=0){return FOCUS_BASE[tier]?.[type==='stone'?0:enchant]||0;}
function normalizeSpecs(specs={}){const out={};for(let t=4;t<=8;t++)out[t]=Math.max(0,Math.min(100,Math.floor(+specs[t]||0)));return out;}
function focusCostEfficiency(specs={},tier=4){const s=normalizeSpecs(specs);return Object.values(s).reduce((a,b)=>a+b,0)*30+(s[tier]||0)*250;}
function focusCost(type,tier,enchant=0,specs={}){const base=baseFocusCost(type,tier,enchant);if(!base)return 0;return Math.ceil(base*Math.pow(.5,focusCostEfficiency(specs,tier)/10000));}
function recipe(type,tier,enchant=0,route='standard'){if(!TYPES[type]||!RAW_QTY[tier]||tier<4&&enchant>0||type==='stone'&&enchant>3)return null;if(route==='heart'&&!supportsHeart(type,tier,enchant))return null;const outputQty=type==='stone'&&enchant>0?2**enchant:1,heart=route==='heart';return{type,tier,enchant,route,outputId:itemId(type,tier,enchant,true),rawId:itemId(type,tier,enchant,false),previousId:previousItemId(type,tier,enchant),heartId:heart?TYPES[type].heart:null,rawQty:RAW_QTY[tier]-(heart?1:0),previousQty:tier===2?0:(type==='stone'&&enchant>0?outputQty:1),heartQty:heart?1:0,outputQty,itemValue:outputItemValue(type,tier,enchant),baseFocus:baseFocusCost(type,tier,enchant),refiningCity:TYPES[type].city};}
function returnRate({focus=false,dailyBonus=0,bonusCity=true}={}){const bonus=.18+(bonusCity?.40:0)+(focus?.59:0)+Math.max(0,+dailyBonus||0)/100;return bonus/(1+bonus);}
function validTime(v){if(!v||String(v).startsWith('0001-'))return NaN;const s=String(v),z=/[zZ]$|[+\-]\d{2}:?\d{2}$/.test(s);return Date.parse(z?s:s+'Z');}
function selectPrice(rows,itemIdValue,side,markets){const allowed=new Set(markets||[]),candidates=(rows||[]).filter(r=>r.item_id===itemIdValue&&(!allowed.size||allowed.has(r.city))).map(r=>{const price=side==='buy'?+r.sell_price_min:+r.buy_price_max,date=side==='buy'?r.sell_price_min_date:r.buy_price_max_date;return{city:r.city,price,date,row:r};}).filter(x=>x.price>0);candidates.sort((a,b)=>side==='buy'?a.price-b.price||validTime(b.date)-validTime(a.date):b.price-a.price||validTime(b.date)-validTime(a.date));return candidates[0]||null;}
function selectSellOrder(rows,itemIdValue,markets){const allowed=new Set(markets||[]),a=(rows||[]).filter(r=>r.item_id===itemIdValue&&(!allowed.size||allowed.has(r.city))&&+r.sell_price_min>0).map(r=>({city:r.city,price:+r.sell_price_min,date:r.sell_price_min_date,row:r}));a.sort((x,y)=>y.price-x.price||validTime(y.date)-validTime(x.date));return a[0]||null;}
function calculate(recipeValue,rows,cfg={}){const r=recipeValue,markets=cfg.markets||[],raw=selectPrice(rows,r.rawId,'buy',markets),previous=r.previousId?selectPrice(rows,r.previousId,'buy',markets):null,heart=r.heartId?selectPrice(rows,r.heartId,'buy',markets):null,output=cfg.saleMode==='relist'?selectSellOrder(rows,r.outputId,markets):selectPrice(rows,r.outputId,'sell',markets);if(!raw||r.previousId&&!previous||r.heartId&&!heart||!output)return null;
  const dailyBonus=cfg.dailyBonuses&&cfg.dailyBonuses[r.type]!=null?+cfg.dailyBonuses[r.type]||0:+cfg.dailyBonus||0,rrr=returnRate({focus:!!cfg.focus,dailyBonus,bonusCity:true}),rrrWithoutFocus=returnRate({focus:false,dailyBonus,bonusCity:true}),undercut=cfg.saleMode==='relist'?Math.max(0,+cfg.undercutPct||0)/100:0,grossSell=cfg.saleMode==='relist'?Math.max(1,Math.floor(output.price*(1-undercut))):output.price,taxRate=Math.max(0,+cfg.taxPct||0)/100,setupRate=cfg.saleMode==='relist'?Math.max(0,+cfg.setupPct||0)/100:0,setupFee=grossSell*setupRate,netRevenue=grossSell*(1-taxRate-setupRate),grossIngredientsCraft=r.rawQty*raw.price+r.previousQty*(previous?.price||0)+r.heartQty*(heart?.price||0),effectiveIngredientsCraft=grossIngredientsCraft*(1-rrr),effectiveIngredients=effectiveIngredientsCraft/r.outputQty;
  const hasCalculatedStationFee=cfg.stationFees!=null||cfg.stationFeePer100!=null,stationFeePer100=Math.max(0,+(cfg.stationFees?.[r.type]??cfg.stationFeePer100??0)||0),stationFee=hasCalculatedStationFee?r.itemValue*stationFeePer100*.001125:Math.max(0,+cfg.stationFee||0),transport=Math.max(0,+cfg.transportPerOutput||0),profit=netRevenue-effectiveIngredients-stationFee-transport,unitCost=effectiveIngredients+stationFee+transport+setupFee,roi=unitCost>0?profit/unitCost*100:null;
  const specs=cfg.specsByType?.[r.type]||cfg.specs||{},fce=focusCostEfficiency(specs,r.tier),focusPerCraft=cfg.focus?focusCost(r.type,r.tier,r.enchant,specs):0,focusBudget=Math.max(0,Math.floor(cfg.focusBudget==null?10000:+cfg.focusBudget||0)),requestedBatch=Math.max(1,Math.floor(+cfg.batchSize||100)),requestedCrafts=Math.ceil(requestedBatch/r.outputQty),maxFocusCrafts=cfg.focus&&focusPerCraft>0?Math.floor(focusBudget/focusPerCraft):Infinity,crafts=Math.min(requestedCrafts,maxFocusCrafts),batch=crafts*r.outputQty,batchLimitedByFocus=crafts<requestedCrafts,focusNeeded=focusPerCraft*requestedCrafts,focusUsed=focusPerCraft*crafts;
  const profitWithoutFocus=netRevenue-grossIngredientsCraft*(1-rrrWithoutFocus)/r.outputQty-stationFee-transport,extraProfitPerCraft=cfg.focus?grossIngredientsCraft*(rrr-rrrWithoutFocus):0,profitPerFocus=cfg.focus&&focusPerCraft>0?extraProfitPerCraft/focusPerCraft:null,confirmedLimit=Math.max(0,Math.floor(+cfg.confirmedBatch||0)),confirmedBatch=confirmedLimit?Math.min(batch,confirmedLimit):null,times=[raw,previous,heart,output].filter(Boolean).map(x=>validTime(x.date)).filter(Number.isFinite),oldestTime=times.length?Math.min(...times):NaN,newestTime=times.length?Math.max(...times):NaN;
  return{...r,raw,previous,heart,output,dailyBonus,rrr,rrrWithoutFocus,grossSell,netRevenue,setupFee,grossIngredients:grossIngredientsCraft,effectiveIngredients,stationFeePer100,stationFee,transport,profit,profitWithoutFocus,roi,batch,requestedBatch,requestedCrafts,crafts,batchLimitedByFocus,missingOutputQty:Math.max(0,requestedBatch-batch),grossRawNeeded:r.rawQty*crafts,grossPreviousNeeded:r.previousQty*crafts,grossHeartNeeded:r.heartQty*crafts,expectedRawConsumed:r.rawQty*crafts*(1-rrr),expectedPreviousConsumed:r.previousQty*crafts*(1-rrr),expectedHeartConsumed:r.heartQty*crafts*(1-rrr),firstBatchCapital:grossIngredientsCraft*crafts+(stationFee+transport+setupFee)*batch,expectedBatchProfit:profit*batch,confirmedBatch,confirmedBatchProfit:confirmedBatch==null?null:profit*confirmedBatch,focusBase:r.baseFocus,focusEfficiency:fce,focusPerCraft,focusBudget,focusNeeded,focusUsed,profitPerFocus,oldestQuoteDate:Number.isFinite(oldestTime)?new Date(oldestTime).toISOString():null,newestQuoteDate:Number.isFinite(newestTime)?new Date(newestTime).toISOString():null,quoteSpreadHours:Number.isFinite(oldestTime)&&Number.isFinite(newestTime)?(newestTime-oldestTime)/36e5:null,saleMode:cfg.saleMode||'instant',batchProfitIsEstimate:confirmedBatch==null};
}
function recipes(types=Object.keys(TYPES),tiers=[2,3,4,5,6,7,8],enchants=[0,1,2,3,4],options={}){const out=[];for(const type of types)for(const tier of tiers)for(const enchant of enchants){if(tier<4&&enchant>0||type==='stone'&&enchant>3)continue;const standard=recipe(type,+tier,+enchant);if(standard)out.push(standard);if(options.includeHearts){const heart=recipe(type,+tier,+enchant,'heart');if(heart)out.push(heart);}}return out;}
function requiredItemIds(recipeList){const s=new Set();for(const r of recipeList){s.add(r.rawId);s.add(r.outputId);if(r.previousId)s.add(r.previousId);if(r.heartId)s.add(r.heartId);}return[...s];}
return{TYPES,RAW_QTY,FOCUS_BASE,itemId,previousItemId,supportsHeart,outputItemValue,baseFocusCost,normalizeSpecs,focusCostEfficiency,focusCost,recipe,recipes,requiredItemIds,returnRate,selectPrice,selectSellOrder,calculate,validTime};
});
